//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet.Migrations.Migrations.All {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201611170838307_FinalDb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201611170838307_FinalDb() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWallet.Migrations.Migrations.All.201611170838307_FinalDb", typeof(_201611170838307_FinalDb).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0da2/cuPF7gf4HQZ/aIue1k/ZwNdZ3yNlOYPQcB97Ntd8CekVvhGqlPUkb2Cjul92H/qT+hVJvPoZPPXbtMwIEa4ocDmeGw5khOfzfb/+d//CwibyvOM3CJD7zT46OfQ/HqyQI4/WZv8vvv/nO/+H7P/5hfhlsHryfm3pvinqkZZyd+V/yfHs6m2WrL3iDsqNNuEqTLLnPj1bJZoaCZPb6+Pjvs5OTGSYgfALL8+a3uzgPN7j8g/x5nsQrvM13KLpOAhxldTn5siiheh/QBmdbtMJn/vXjP1EU4fzokoDIQ5wdkdY5fsgz33sbhYhgtMDRve+hOE5ylBN8Tz9leJGnSbxebEkBipaPW0zq3aMow/U4TrvqpkM6fl0MadY1bECtdlmebCwBnrypaTTjmztR2m9pSKhYkuqxGHVJyTP/x12wxrnv8V2dnkdpUQ0ic8Wao6rpK0+o8KoVDyJFxb9X3vkuyncpPovxLk9R9Mr7uLuLwtU/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
