// <auto-generated />
namespace MyWallet.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BudgetAddNameProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BudgetAddNameProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081738245_BudgetAddNameProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
